### ISSUE TITLE
Find CustomerNo Example

### ISSUE THREAD

**Issue by timint** [billogram/billogram-v2-api-php-lib#6]
Does the library allow creating invoices without a customer no? I have an issue where every API order creates duplicate customer profiles. The example file is pretty insufficient perhaps an example would save integrators a lot of time.

**Comment by AndreasHogstrom** [comment]
The library will probably allow you to send a request without a ```customer_no```, but our servers will return with an error, that ```customer_no``` is missing.

I'm not sure i understand your issue.
Are you calling ```$api->customers->create()``` before every invoice create call? If you already have a customer profile for the customer you wish to create an invoice for, you should instead just supply that profiles' ```customer_no``` when creating the invoice, instead of creating a new profile.

If you need any further support with API-related questions, please email support@billogram.com and they will try to help you. This issue forum is primarily for issues regarding the actual PHP library.

I do agree with you that the examples may be a bit lacking, I will do my best to try to get more examples added in the future :+1:

**Comment by timint** [comment]
Indeed it did allow it but the API halted.

Basically I don't want duplicate customer profiles. When passing an order I need a customer_no. That's no trouble creating one. But if the customer has ordered before I get a duplicate contact.

There is no PHP example what procedure is recommended for finding the customer first and not creating a new profile if one already exsits.

Apology for hijacking a thread. Basically a good example for the procedure above in this library package would save integrators a lot of time from reverse engineering the framework. The extended examples in the documentation on the website are for Python.

**Comment by emilsundberg** [comment]
@timint Did you solve this issue? I'm having the same troubles and have a hard time understanding the PHP lib. I'm thinking about writing my own implementation instead.

**Comment by timint** [comment]
The solution is to
1. Check if customer profile exists
2. Create the customer if it does not exist
3. Create the order and supply the customer id

I agree building an own implementation might be useful. But the API itself has several limitations, just as the integration package is a second bottleneck.

There is no option to get the raw http request or response. You can't list orders on created date nor limit the number of results. There is no csv export in billogram, and exporting your own ocer the api the list of billograms doesnt hold enough info. And crawling every invoice has so low performance you are stuck with a timeout. I have had trouble in almost every task.
