### ISSUE TITLE
Request more php examples

### ISSUE THREAD

**Issue by samedgecombe** [billogram/billogram-v2-api-php-lib#7]
Hi,

I am developing my site to connect with Billogram's API and have got stuck doing the following. The examples.php creates a new customer, but I would like to do the following

1. Check if customer with a customer_no exists first,
2. If not then create the customer,
3. If the customer exists then update the customer's details (name, address)

Would this be possible to add to the examples.php?

**Comment by AndreasHogstrom** [comment]
Hey @samedgecombe,

That's great to hear, I'm sorry you got stuck. I cannot provide you with full code examples for you at this time, but your process of thought is correct!

* Do a fetch for `customer_no`.
* If it exists, use the `$obj->update($updatedData)` function.
* Otherwise, use the `$api->customers->create($data)` function.

You can also read more about how customers are managed in our API documentation at https://billogram.com/api/documentation#customers .

If you have further inquires or issues, please contact support@billogram.com, issues in this repository is primarily for problems in the library itself, but I will note your feedback and will try to add more examples in the future.

Thank you
//Andreas
